-- Auto-generated from schema-map-postgres.yaml (map@sha1:FAEA49A5D5F8FAAD9F850D0F430ED451C5C1D707)
-- engine: postgres
-- table:  kms_health_checks

CREATE TABLE IF NOT EXISTS kms_health_checks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NULL,
  kms_key_id  BIGINT NULL,
  status TEXT NOT NULL,                           -- 'up','degraded','down'
  latency_ms INTEGER NULL,
  error TEXT NULL,
  checked_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_kms_hc_status CHECK (status IN ('up','degraded','down'))
);
